on:
  schedule:
    - cron:  '0 0 * * *'
    # scheduled at 00:00 every Day

  workflow_dispatch:  # click the button on Github repo!

name: sync tracking branches

jobs:
  zotero_sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync zotero.zotero with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout zotero.zotero
      uses: actions/checkout@v2.3.4
      with:
        ref: zotero.zotero
        # submodules: 'recursive'     ### may be needed in your situation

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull (Fast-Forward) upstream changes
      id: sync_zotero
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
      with:
        upstream_repository: microsoft/winget-pkgs
        upstream_branch: master
        target_branch: zotero.zotero
        git_pull_args: --ff-only                    # optional arg use, defaults to simple 'pull'
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication

  qbittorrent_sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync qbittorrent.qbittorrent with upstream latest

    steps:

     # Step 1: run a standard checkout action, provided by github
    - name: Checkout qbittorrent.qbittorrent
      uses: actions/checkout@v2.3.4
      with:
        ref: qbittorrent.qbittorrent
        # submodules: 'recursive'     ### may be needed in your situation

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull (Fast-Forward) upstream changes
      id: sync_qbittorrent
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
      with:
        upstream_repository: microsoft/winget-pkgs
        upstream_branch: master
        target_branch: qbittorrent.qbittorrent
        git_pull_args: --ff-only                    # optional arg use, defaults to simple 'pull'
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication

  mpc-hc_sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync mpc-hc with upstream latest

    steps:

     # Step 1: run a standard checkout action, provided by github
    - name: Checkout clsid2.mpc-hc
      uses: actions/checkout@v2.3.4
      with:
        ref: clsid2.mpc-hc
        # submodules: 'recursive'     ### may be needed in your situation

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull (Fast-Forward) upstream changes
      id: sync_mpc-hc
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
      with:
        upstream_repository: microsoft/winget-pkgs
        upstream_branch: master
        target_branch: clsid2.mpc-hc
        git_pull_args: --ff-only                    # optional arg use, defaults to simple 'pull'
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication

  dingtalk_sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync alibaba.dingtalk with upstream latest

    steps:

     # Step 1: run a standard checkout action, provided by github
    - name: Checkout alibaba.dingtalk
      uses: actions/checkout@v2.3.4
      with:
        ref: alibaba.dingtalk
        # submodules: 'recursive'     ### may be needed in your situation

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull (Fast-Forward) upstream changes
      id: sync_dingtalk
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
      with:
        upstream_repository: microsoft/winget-pkgs
        upstream_branch: master
        target_branch: alibaba.dingtalk
        git_pull_args: --ff-only                    # optional arg use, defaults to simple 'pull'
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication

   # Step 4: Print a helpful timestamp for your records (not required, just nice)
    - name: Timestamp
      run: date
